Will
jo5huar3/cougarecho pull request #14
Opened 2024-11-16 20:24 UTC by WilliamNguyen21

Create New Playlist Page Without Playlist Image

2024-11-16 23:37 UTC, jo5huar3 commented on routes/api.js
> +  origin: 'http://localhost:5173', // Your React app URL
remove this

2024-11-16 23:39 UTC, jo5huar3 commented on routes/api.js
> +import cors from 'cors';
remove

2024-11-17 00:34 UTC, jo5huar3 requested changes
I added a couple things to delete. Things like cors  are already defined

2024-11-17 09:48 UTC, WilliamNguyen21 reviewed
fix create playlist page, and working library page,
- stilll working on images for playlist

2024-11-17 17:03 UTC, merged